[#1011] Dark mode
Electric-Coin-Company/zashi-android pull request #1476
Opened 2024-06-18 12:34 UTC by HonzaR

- These changes bring the dark theme into the entire app UI
- All screens and UI widgets are now properly colored for both Light and Dark theme
- The PR also brings a few other mostly minor UI changes to simplify the dark mode adoption
- Closes #1011
- Closes https://github.com/Electric-Coin-Company/zashi/issues/32
- Closes #1410
- Closes #1337

<img src="https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/c853cef7-8d07-431e-a679-737a8664b40f" width="300" />
<img src="https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/4a8ecd6b-b4c7-40da-9ca1-8f3cb6d5ca86" width="300" />
<img src="https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/f84d10cf-0028-481e-a3f3-8d8848d45074" width="300" />

> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] **Self-review** your own code in GitHub's web interface[^1]
- [ ] Add **automated tests** as appropriate
- [ ] Update the [**manual tests**](../blob/main/docs/testing/manual_testing)[^2] as appropriate
- [ ] Check the **code coverage**[^3] report for the automated tests
- [x] Update **documentation** as appropriate (e.g [**README.md**](../blob/main/README.md), [**Architecture.md**](../blob/main/docs/Architecture.md), [**CHANGELOG.md**](../blob/main/CHANGELOG.md), etc.)
- [x] **Run the app** and try the changes
- [x] Pull in the latest changes from the **main** branch and **squash** your commits before assigning a reviewer[^4]

> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes that modify the UI.

# Reviewer

- [x] Check the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) **checklist**
- [ ] Perform an **ad hoc review**[^5]
- [ ] Review the **automated tests**
- [ ] Review the **manual tests**
- [ ] Review the **documentation**, [**README.md**](../blob/main/README.md), [**Architecture.md**](../blob/main/docs/Architecture.md), etc. as appropriate
- [ ] **Run the app** and try the changes[^6]

[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed. Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck -PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true` for Android modules._
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
[^5]: _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
[^6]: _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

2024-06-18 13:46 UTC, LukasKorba approved these changes
utACK

2024-06-18 16:03 UTC, Milan-Cerovsky requested changes
Good PR 👍  Got a few minor comments. Since it's a huge one I'll do a second review too.

2024-06-19 06:46 UTC, HonzaR commented on ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Checkbox.kt
> +        BlankSurface {
That's a good point. We could leverage the Preview `showBackground` and `backgroundColor` for the UI components from the design-lib module. I'm in favor of keeping our Previews from the ui-lib module as they are, as we have blank or grid variants there to align with the final screen look as closely as possible. Filed a follow-up on this change #1477

2024-06-19 06:52 UTC, HonzaR commented on ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Chip.kt
>              style = MaterialTheme.typography.bodyLarge,
We're not using `MaterialTheme.typography` in the client ui-lib module. We're using it only here in the design-lib module, which seems fine to me. What do you think?

2024-06-19 10:15 UTC, Milan-Cerovsky approved these changes

2024-06-19 11:37 UTC, HonzaR commented on ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Dialog.kt
> +            modifier.then(
Good catch.

2024-06-19 11:40 UTC, HonzaR commented on ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/warning/AndroidNotEnoughSpace.kt
> +    context: Context,
Correct, fixed.

2024-06-19 11:41 UTC, HonzaR commented on ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/warning/view/NotEnoughSpaceView.kt
> +            onClick = onSystemStettings,
Good catch. Thank you.

2024-06-19 11:48 UTC, HonzaR commented on ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
> +        Twig.info { "Not enough free space" }
That's a good idea. I just filed an issue for this improvement #1478.

2024-06-19 11:49 UTC, HonzaR commented on ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
> +        Twig.info { "App update available" }
As above #1478.

2024-06-19 11:49 UTC, HonzaR commented on ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/warning/AndroidNotEnoughSpace.kt
> +    if (isEnoughFreeSpace == true) {
As above #1478.

2024-06-19 12:09 UTC, merged