Update deploy.yml
Electric-Coin-Company/zashi-android pull request #1683
Opened 2024-11-14 20:07 UTC by y4ssi

Fixing CI

2024-11-15 09:00 UTC, HonzaR requested changes
Looks good to me. I just block this until we finish the current Zashi release and re-review it after it.

2024-11-20 14:46 UTC, daira commented on .github/workflows/deploy.yml
> +          echo $FIREBASE_RELEASE_JSON_BASE64 | base64 --decode > app/src/release/google-services.json
```suggestion
          echo "$FIREBASE_DEBUG_JSON_BASE64" | base64 --decode > app/src/debug/google-services.json
          echo "$FIREBASE_RELEASE_JSON_BASE64" | base64 --decode > app/src/release/google-services.json
```

2024-11-20 14:48 UTC, daira commented on .github/workflows/deploy.yml
> +        if: ${{ env.FIREBASE_DEBUG_JSON_BASE64 != '' && env.FIREBASE_RELEASE_JSON_BASE64 != '' }}
If the syntax with double quotes causes a problem, note that it also occurs on lines 67-71.

2024-11-20 14:49 UTC, daira commented on .github/workflows/deploy.yml
> +          echo $SIGNING_KEYSTORE_BASE_64 | base64 --decode > $SIGNING_KEY_PATH
```suggestion
          echo "$SIGNING_KEYSTORE_BASE_64" | base64 --decode > "$SIGNING_KEY_PATH"
```

2024-11-20 14:49 UTC, daira commented on .github/workflows/deploy.yml
> +          zip -r $MAPPINGS_ZIP_PATH . -i app/build/outputs/mapping/*/mapping.txt
```suggestion
          mkdir "$ARTIFACTS_DIR_PATH"
          zip -r "$BINARIES_ZIP_PATH" . -i app/build/outputs/apk/*/*.apk app/build/outputs/apk_from_bundle/*/*.apk app/build/outputs/bundle/*/*.aab
          zip -r "$MAPPINGS_ZIP_PATH" . -i app/build/outputs/mapping/*/mapping.txt
```

2025-10-21 10:41 UTC, Milan-Cerovsky commented
is this still relevant? if not close it @y4ssi

2025-10-21 14:51 UTC, closed without merging